### ISSUE TITLE
CLI: reducing printed information when using import-shared-part command

### ISSUE THREAD

**Issue by MelSFNL** [silverfin/silverfin-cli#37]
**Is your feature request related to a problem? Please describe.**
When importing all shared parts from a firm, a lot of API call responses etc. are printed. This is not informative and floods the terminal. 

**Describe the solution you'd like**
Either:
(1) Add a --verbose option which reduces the printed information when using the import-shared-part command
or:
(2) Make the --verbose option standard and include another option to print all info (i.e. the other way around)

**Describe alternatives you've considered**
None

**Additional context**
Small and insignificant feature request, but needed to clear it from my to do list

**Comment by AgustinSilverfin** [comment]
The reason why we started like this (verbose by default) was to make explicit every time that we were making an API request. So that way we could be conscious while using the CLI and not abuse of those requests.
But I agree with you,  it's one of the things that I would like to change as well, whenever we have the time to do it.
